spring.application.name=addition
server.port:7070
spring.database.url=jdbc:mysql://localhost:3306/addition
spring.datasource.username=root
spring.datasource.password=bca123
spring.jpa.hibernate.ddl.auto=update