spring.application.name=project6
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.url=jdbc:mysql://localhost:3306/student_management
spring.jpa.hibernate.ddl-auto=update
